/* eslint-disable prettier/prettier */
const data = [
  {
    id: 1,
    isNotification: false,
    name: 'Name 1',
    description: 'description 1',
    url: 'https://reactnative.dev/img/tiny_logo.png',
  },
  {
    id: 2,
    isNotification: false,
    name: 'Name 2',
    description: 'description 2',
    url: 'https://reactnative.dev/img/tiny_logo.png',
  },
  {
    id: 3,
    isNotification: false,
    name: 'Name 3',
    description: 'description 3',
    url: 'https://reactnative.dev/img/tiny_logo.png',
  },
  {
    id: 4,
    isNotification: false,
    name: 'Name 4',
    description: 'description 4',
    url: 'https://reactnative.dev/img/tiny_logo.png',
},
{
    id: 5,
    isNotification: false,
    name: 'Name 5',
    description: 'description 5',
    url: 'https://reactnative.dev/img/tiny_logo.png',
},
{
    id: 6,
    isNotification: false,
    name: 'Name 6',
    description: 'description 6',
    url: 'https://reactnative.dev/img/tiny_logo.png',
},
{
    id: 7,
    isNotification: false,
    name: 'Name 7',
    description: 'description 7',
    url: 'https://reactnative.dev/img/tiny_logo.png',
},
{
    id: 8,
    isNotification: false,
    name: 'Name 8',
    description: 'description 8',
    url: 'https://reactnative.dev/img/tiny_logo.png',
},
{
    id: 9,
    isNotification: false,
    name: 'Name 9',
    description: 'description 9',
    url: 'https://reactnative.dev/img/tiny_logo.png',
},
{
    id: 10,
    isNotification: false,
    name: 'Name 10',
    description: 'description 10',
    url: 'https://reactnative.dev/img/tiny_logo.png',
},
{
  id: 11,
  isNotification: false,
  name: 'Name 11',
  description: 'description 10',
  url: 'https://reactnative.dev/img/tiny_logo.png',
},
{
  id: 12,
  isNotification: false,
  name: 'Name 12',
  description: 'description 10',
  url: 'https://reactnative.dev/img/tiny_logo.png',
},
{
  id: 13,
  isNotification: false,
  name: 'Name 13',
  description: 'description 10',
  url: 'https://reactnative.dev/img/tiny_logo.png',
},
{
  id: 14,
  isNotification: false,
  name: 'Name 14',
  description: 'description 10',
  url: 'https://reactnative.dev/img/tiny_logo.png',
},
{
  id: 15,
  isNotification: false,
  name: 'Name 15',
  description: 'description 10',
  url: 'https://reactnative.dev/img/tiny_logo.png',
},
{
  id: 16,
  isNotification: false,
  name: 'Name 16',
  description: 'description 10',
  url: 'https://reactnative.dev/img/tiny_logo.png',
},
{
  id: 17,
  isNotification: false,
  name: 'Name 17',
  description: 'description 10',
  url: 'https://reactnative.dev/img/tiny_logo.png',
},
{
  id: 18,
  isNotification: false,
  name: 'Name 18',
  description: 'description 10',
  url: 'https://reactnative.dev/img/tiny_logo.png',
},
{
  id: 19,
  isNotification: false,
  name: 'Name 19',
  description: 'description 10',
  url: 'https://reactnative.dev/img/tiny_logo.png',
},
{
  id: 20,
  isNotification: false,
  name: 'Nam 20',
  description: 'description 10',
  url: 'https://reactnative.dev/img/tiny_logo.png',
},
];
export {data};
